spring.application.name=config-server

server.port=8762

spring.cloud.config.server.git.uri=${CONFIG_GIT_URI:https://github.com/sezerdemir7/ecommerce-config-repo.git}
spring.cloud.config.server.git.default-label=${CONFIG_GIT_BRANCH:main}
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.force-pull=true

eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

management.endpoints.web.exposure.include=*

spring.cloud.config.server.git.username=sezerdemir7
spring.cloud.config.server.git.password=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
